apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "400Mi"
      args:
        - "--dockerfile=$DOCKERFILE"
        - "--context=dir://workspace"
        - "--destination=$STORE/$IMAGE:$TAG"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /secret
        - name: media-data
          mountPath: /workspace
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secret/kaniko-secret.json
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret
    - name: media-data
      persistentVolumeClaim:
        claimName: media-vol