kind: Deployment
apiVersion: apps/v1
metadata:
  name: gui
  labels:
    app: gui

spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
        - name: gui
          image: europe-north1-docker.pkg.dev/devsecopsexamproject/exam-project/ui:latest
          imagePullPolicy: Never
          ports:
            - name: incomming
              containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: gui-service
spec:
  ports:
    - name: websecure
      port: 80
      targetPort: incomming

  selector:
    app: gui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gui-ingress
spec:
  rules:
  # - host: devg4.dk.eu.org
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gui-service
            port:
              name: websecure
