steps:
- name: 'alpine'
  dir: 'GUI'
  entrypoint: 'sed'
  args: ['/^RUN --mount=type=secret/,+1 s/^/#/', '-i', 'Dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  dir: 'GUI'
  args: ['build', '-t', 'europe-north1-docker.pkg.dev/devsecopsexamproject/exam-project/ui', '.']
images: ['europe-north1-docker.pkg.dev/devsecopsexamproject/exam-project/ui']
