steps:
- name: 'alpine'
  entrypoint: 'sed'
  args: ['s/^RUN --mount=type=secret/#&/', '-i', 'Dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-north1-docker.pkg.dev/devsecopsexamproject/exam-project/ui', '.']
images: ['europe-north1-docker.pkg.dev/devsecopsexamproject/exam-project/ui']