# add to docker compose 
services:
  db:
    build: ./DB
    env_file:
      -./DB/.env
    # volume to make the data persistent
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always