# Persistent Volume, claimed by the pods for storing the database
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    type: google-ssd
spec:
  storageClassName: ssd     # class created in sc.yaml
  capacity:
    storage: 6Gi            # total capacity for this persistent volume
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:        # use a Google Persistent Disk
    pdName: postgres-disk   # replace with the name of your disk
    fsType: ext4            # file system type
