name: Build and Push to Google Artifact Registry

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: devsecopsexamproject
  GAR_LOCATION: europe-west3

jobs:
  build-and-push:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        
      - name: Checkout API
        uses: actions/checkout@v4
        with:
          repository: 'devopsexamg4/api'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_API }}
          path: './API'
        
      - name: Checkout DB
        uses: actions/checkout@v4
        with:
          repository: 'devopsexamg4/db'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_DB }}
          path: './DB'
          
      - name: Checkout UI
        uses: actions/checkout@v4
        with:
          repository: 'devopsexamg4/ui'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_UI }}
          path: './UI'

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY}}
      - name: List directory contents
        run: ls -la ${{ github.workspace }}

      - name: Build and Push Container
        run: |-
          cd ${{ github.workspace }}
          docker-compose build
          for service in $(docker-compose config --services); do
            docker-compose pull $service
            image_id=$(docker-compose images -q $service)
            image_tag="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${service}:${{ github.sha }}"
            echo "image_id: $image_id"
            echo "image_tag: $image_tag"
            docker tag $image_id $image_tag
            docker push $image_tag
          done
