name: Build and Push to Google Artifact Registry

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: devsecopsexamproject
  GAR_LOCATION: europe-west3

jobs:
  build-and-push:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          token: ${{ secrets.SSH_PRIVATE_KEY }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY}}

      - name: Build and Push Container
        run: |-
          docker-compose build
          docker tag examProject "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ github.sha }}"
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ github.sha }}"
