name: Build and Push to Google Artifact Registry

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: devsecopsexamproject
  GAR_LOCATION: europe-north1
  GAR_URL: europe-north1-docker.pkg.dev/devsecopsexamproject/exam-project/ui
  SERVICE: ui

jobs:
  build-and-push:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

          
      - name: "Docker auth"
        run: |-
              gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet
              
      - name: Build and Push Container
        secrets: |
          "secret_1=${{ secrets.KEY }}"
          "secret_2=${{ secrets.DEBUG }}"
          "secret_3=${{ secrets.ALLOWED_HOSTS }}"
          "secret_4=${{ secrets.SU_PASS }}"
          "secret_5=${{ secrets.SU_USER }}"
          "secret_6=${{ secrets.SU_EMAIL }}"
        run: |-
          cd ${{ github.workspace }}
          docker build . -t  ${{env.GAR_URL}}:latest
          docker push ${{env.GAR_URL}}
          