name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        # make sure the git files are up to date
        git pull --recurse-submodules
        git submodule update --init --remote --recursive
        # get all requirement.txt files and call pip install on them
        echo "installing requirements"
        git ls-files --recurse-submodules --full-name | grep -E *requirements.txt 2>/dev/null  | while read line; do echo installing requirements from $line ; pip install -r $line ; done
        echo "done installing requirements"
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files --recurse-submodules '*.py' ':!:*conf.py')
